version: '2'
services:
  database:
    image: bistech/orclxe18c:latest
    #volumes:
    #  - /home/oracle/oradata:/opt/oracle/oradata # persistent oracle database data.
    ports:
      - 1521:1521
      - 8080:8080
      - 5500:5500
